name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  sync-test:
    runs-on: ubuntu-latest
    env:
      BATON_TOKEN: ${{ secrets.BATON_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build baton-pagerduty
        run: go build -o baton-pagerduty ./cmd/baton-pagerduty
      - name: Test syncing
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: './baton-pagerduty'
          baton-entitlement: 'role:user-user:member'
          baton-principal: 'PFSMLDZ'
      - name: Test account provisioning
        uses: ConductorOne/github-workflows/actions/account-provisioning@v4
        with:
          connector: './baton-pagerduty'
          account-email: 'baton-ci-test@conductorone.com'
          account-profile: '{"name": "Baton CI Test User", "role": "limited_user"}'
